# Generated by Django 5.2.8 on 2025-11-16 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "video_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("video_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "processed_video_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("processing", "processing"),
                            ("completed", "completed"),
                            ("failed", "failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("frames_per_second", models.IntegerField(default=2)),
                ("confidence_threshold", models.FloatField(default=0.5)),
                ("total_frames", models.IntegerField(default=0)),
                ("processed_frames", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "processing_sessions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id"], name="processing__session_0ada96_idx"
                    ),
                    models.Index(
                        fields=["status"], name="processing__status_c86556_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="processing__created_ef1921_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Frame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_number", models.IntegerField(db_index=True)),
                ("frame_path", models.CharField(max_length=500)),
                ("frame_url", models.CharField(max_length=500)),
                ("timestamp", models.FloatField(default=0.0)),
                ("total_detections", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frames",
                        to="core.processingsession",
                    ),
                ),
            ],
            options={
                "db_table": "frames",
                "ordering": ["session", "frame_number"],
            },
        ),
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_id", models.IntegerField()),
                ("class_name", models.CharField(db_index=True, max_length=100)),
                ("confidence", models.FloatField(db_index=True)),
                ("bbox_x1", models.FloatField()),
                ("bbox_y1", models.FloatField()),
                ("bbox_x2", models.FloatField()),
                ("bbox_y2", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="core.frame",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="core.processingsession",
                    ),
                ),
            ],
            options={
                "db_table": "detections",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_detections", models.IntegerField(default=0)),
                ("unique_logos", models.JSONField(default=list)),
                ("logo_counts", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="core.processingsession",
                    ),
                ),
            ],
            options={
                "db_table": "session_summaries",
            },
        ),
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_id", models.IntegerField()),
                ("class_name", models.CharField(max_length=100)),
                ("confidence", models.FloatField()),
                ("rank", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "detection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifications",
                        to="core.detection",
                    ),
                ),
            ],
            options={
                "db_table": "classifications",
                "ordering": ["detection", "rank"],
                "indexes": [
                    models.Index(
                        fields=["detection", "rank"],
                        name="classificat_detecti_6adec4_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="frame",
            index=models.Index(
                fields=["session", "frame_number"], name="frames_session_2bc742_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="frame",
            index=models.Index(fields=["created_at"], name="frames_created_4f678f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="frame",
            unique_together={("session", "frame_number")},
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(
                fields=["session", "class_name"], name="detections_session_1b2508_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(fields=["frame"], name="detections_frame_i_1b3254_idx"),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(
                fields=["class_name", "confidence"],
                name="detections_class_n_e449e1_idx",
            ),
        ),
    ]
