# Generated by Django 5.2.8 on 2025-11-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingsession",
            name="create_video",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="processingsession",
            name="enable_classification",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="processingsession",
            name="model_weight",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
