# Generated by Django 5.2.8 on 2025-11-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_session_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processingsession",
            name="create_video",
        ),
        migrations.RemoveField(
            model_name="processingsession",
            name="enable_classification",
        ),
        migrations.RemoveField(
            model_name="processingsession",
            name="model_weight",
        ),
        migrations.AddField(
            model_name="processingsession",
            name="settings",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
