# Generated by Django 5.2.8 on 2026-05-17 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_processingsession_create_video_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="frame",
            name="ocr_summary",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Ocr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_key", models.CharField(default="raw", max_length=64)),
                ("custom_prompt", models.TextField(blank=True)),
                ("raw_text", models.TextField(blank=True)),
                ("raw_lines", models.JSONField(default=list)),
                ("formatted", models.JSONField(blank=True, null=True)),
                ("roi", models.JSONField(blank=True, null=True)),
                ("confidence_avg", models.FloatField(default=0.0)),
                ("format_error", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "detection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr",
                        to="core.detection",
                    ),
                ),
                (
                    "frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_results",
                        to="core.frame",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_results",
                        to="core.processingsession",
                    ),
                ),
            ],
            options={
                "db_table": "ocr_results",
                "ordering": ["frame", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "frame"],
                        name="ocr_results_session_673dcf_idx",
                    ),
                    models.Index(
                        fields=["template_key"], name="ocr_results_templat_a7f22d_idx"
                    ),
                ],
            },
        ),
    ]
