# Generated by Django 5.2.8 on 2026-05-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_customocrtemplate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomOcrTemplate",
        ),
    ]
