# Generated by Django 5.2.8 on 2026-05-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_delete_customocrtemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomOcrTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("sport", models.CharField(blank=True, db_index=True, max_length=64)),
                ("description", models.TextField(blank=True)),
                ("regions", models.JSONField(default=list)),
                ("system_prompt", models.TextField(blank=True)),
                ("multimodal", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "custom_ocr_templates",
                "ordering": ["-updated_at"],
            },
        ),
    ]
