# Generated by Django 5.2.8 on 2026-05-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_customocrtemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="SportPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("sport", models.CharField(blank=True, db_index=True, max_length=64)),
                ("description", models.TextField(blank=True)),
                ("prompt", models.TextField()),
                ("reference_image_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sport_prompts",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.DeleteModel(
            name="CustomOcrTemplate",
        ),
    ]
