# Generated by Django 5.2.8 on 2026-06-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_sportprompt_allowed_brands"),
    ]

    operations = [
        migrations.AddField(
            model_name="frame",
            name="s3_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="frame",
            name="frame_path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
