# Generated by Django 5.2.8 on 2026-06-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_frame_s3_key_alter_frame_frame_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="processingsession",
            name="attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="processingsession",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="processingsession",
            name="heartbeat_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="processingsession",
            name="run_params",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="processingsession",
            name="source_is_local",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="processingsession",
            name="source_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="processingsession",
            name="stop_reason",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="processingsession",
            name="video_fps",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="processingsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("queued", "queued"),
                    ("processing", "processing"),
                    ("completed", "completed"),
                    ("failed", "failed"),
                    ("interrupted", "interrupted"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="processingsession",
            index=models.Index(
                fields=["status", "heartbeat_at"], name="processing__status_4b34b7_idx"
            ),
        ),
    ]
