# Generated by Django 5.2.8 on 2026-06-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_processingsession_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="frame",
            name="ocr_job_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
